/**
 * Identity Transfer — Export/Import via QR / link (PWA wrapper).
 *
 * Crypto lives in ./transfer-crypto (shared with the native app). This file only
 * does base64 + URI wrapping. The transfer code is auto-generated by
 * generateTransferCode() — callers no longer pass a user-typed PIN.
 */
import type { BeanPoolIdentity } from './identity';
import { encryptIdentity, decryptIdentity as decryptEnvelope, generateTransferCode } from './transfer-crypto';

export { generateTransferCode };

function bytesToBase64(bytes: Uint8Array): string {
    let binary = '';
    for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
    return btoa(binary);
}

function base64ToBytes(b64: string): Uint8Array {
    const binary = atob(b64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
}

export async function exportIdentity(identity: BeanPoolIdentity, code: string): Promise<string> {
    const envelope = await encryptIdentity(identity, code);
    return `${window.location.origin}/?import=${encodeURIComponent(bytesToBase64(envelope))}`;
}

export async function decryptIdentity(uri: string, code: string): Promise<BeanPoolIdentity> {
    const httpsMatch = uri.match(/[?&]import=(.+?)(?:&|$)/);
    const legacyMatch = uri.match(/beanpool:\/\/import\?d=(.+)/);
    let b64: string;
    if (httpsMatch) {
        b64 = decodeURIComponent(httpsMatch[1]);
    } else if (legacyMatch) {
        b64 = decodeURIComponent(legacyMatch[1]);
    } else {
        throw new Error('Invalid import URI');
    }
    return decryptEnvelope(base64ToBytes(b64), code);
}
